#імпортування файлів
import os
import time
import random
import sys
import sounddevice as sd
import scipy.io.wavfile as wav
from colorama import init, Fore, Style
#шлях до поточної папки
PATH= os.getcwd()
sound_on=True
sound_txt="ВКЛ"
menu=0
#абсолютний шлях до файлу
def getPath(name_file):
    return f"{PATH}\\{name_file}"
#очищення екрану
def clear_scr():
    os.system('cls' if os.name == 'nt' else 'clear')
#друк кольрового тексту
def color_txt(txt='Hello', color=Fore.RED):
    print(color + txt + Style.RESET_ALL)
#фінкція звуку
def play_sound(sound_file):
    sound_file=getPath(sound_file)
    if sound_on:
        try:
            rate,data=wav.read(sound_file)
            sd.play(data,rate)
        except:
            color_txt(txt="Помилка звуку", color=Fore.RED)
#анімація тексту - друк по символьно
def type_txt(txt='Hello', color=Fore.WHITE, delay=0.1):
    play_sound("друк тексту.wav")
    for char in txt:  
        print(color+char+Style.RESET_ALL, end="", flush=True)
        time.sleep(delay)
#рух емодзі вперед
def animate_forward(emoji='🧑🏼'):
    for i in range(10):
        clear_scr()
        print(i*" "+emoji)
        time.sleep(0.2)
#заставка гри
art= r"""
🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪
🟪⬛⬛⬛🟪⬛⬛⬛🟪⬛⬛⬛🟪🟪⬛🟪🟪⬛🟪⬛🟪🟪⬛🟪🟪⬛⬛⬛🟪🟪⬛🟪🟪⬛🟪⬛🟪🟪⬛🟪🟪
🟪🟪⬛🟪🟪⬛🟪🟪🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪
🟪🟪⬛🟪🟪⬛⬛⬛🟪⬛⬛⬛🟪⬛🟪⬛🟪⬛⬛🟪🟪⬛🟪⬛🟪⬛⬛⬛🟪⬛🟪⬛🟪⬛⬛⬛🟪⬛🟪⬛🟪
🟪🟪⬛🟪🟪⬛🟪🟪🟪⬛⬛🟪🟪⬛⬛⬛🟪⬛🟪⬛🟪⬛⬛⬛🟪⬛⬛🟪🟪⬛⬛⬛🟪⬛🟪⬛🟪⬛⬛⬛🟪
🟪🟪⬛🟪🟪⬛⬛⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪⬛🟪
🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪
"""
#програв іди сюди
def lose():
    color_txt(txt="😂Якщо не щастить купи слона🐘", color=Fore.CYAN)
    while True:
        slon=input("😂Купи слона🐘  ")
        color_txt(txt=f"😂Усі кажуть {slon}, а ти візми і купи слона🐘", color=Fore.CYAN)
#гарпун у горах
def garpun():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЗ гарпуном ми митєво підіймемося", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n        *********       ", delay=0.1)
    play_sound("garpun.wav")
    play_sound("die3.wav")
    time.sleep(4)
    color_txt(txt="😔Нажаль ви програли❌. Трос обірвався")
    lose() 
#гарпун у горах коли сам
def garpun1():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЗ гарпуном ми митєво підіймемося", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n        *********       ", delay=0.1)
    play_sound("garpun.wav")
    garpun=random.randint(1,20)
    if garpun==11:
        play_sound("die3.wav")
        time.sleep(4)
        color_txt(txt="😔Нажаль ви програли❌. Трос обірвався")
        lose() 
    else:
        time.sleep(4)
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nОсь він Лабіринт 🟥Червоного 🐉Дракона", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nТи 2️⃣другий хто дістався сюди живий🙂", delay=0.1)
        time.sleep(1)
#печера
def pechera():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТоді пішли через печеру.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n        *********       ", color=Fore.CYAN, delay=0.1)
    time.sleep(5)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nНа нас йдуть 🕷️павуко-змії🐍❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("удар.wav")
    time.sleep(1)
    a=random.randint(1,10)
    if a==random.randint(1,10):
        play_sound("удар.wav")
        time.sleep(1)
        play_sound("die2.wav")
        time.sleep(4)
        color_txt(txt="😔Нажаль ви програли❌. У печері небезпечно")
        lose()
    else:
        play_sound("🥷🏼🧙🏼 ⚔️ 🕷️🐍")
        time.sleep(1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(5)
        type_txt(txt="\n😮‍💨Накінець то вийшли", color=Fore.CYAN, delay=0.1)
        time.sleep(1)    
#печера сам
def pechera1():
    type_txt(txt="\n        *********       ", color=Fore.CYAN, delay=0.1)
    time.sleep(5)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nПощастило що є печера\n", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("trol.wav")
    time.sleep(3)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЦе 🧌троль? Споробую пройти 🤫тихо \n", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    trol=random.randint(1,10)
    if trol==random.randint(1,10):
        play_sound("удар.wav")
        time.sleep(1)
        play_sound("die1.wav")
        time.sleep(4)
        color_txt(txt="Нажаль ви програли. У печері небезпечно та ще й з тролем")
        lose()
    else:
        print("🥷🏼               🧌")
        time.sleep(1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(5)
        type_txt(txt="\n😮‍💨Накінець то вийшов", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
#пролог
def prolog():
    clear_scr()
    you=input("Ведіть своє ім'я(українською)")
    clear_scr()
    type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🥱Ех❗Піду прогуляюсь.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    print("\n         ********          ")
    time.sleep(1.5)
    clear_scr()
    type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n😯О❗ Старий ігровий автомат.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЯк він ▶️вмикається❓ О знайшов❗", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🎮Автомат:", color=Fore.RED, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nБажаєте увійти до Верховної Імперії❓", color=Fore.RED, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nНу можна трохи пограти", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n         ****на 13 рівні****         ", color=Fore.CYAN, delay=0.1)
    time.sleep(2)
    clear_scr()
    type_txt(txt="🎮Автомат:", color=Fore.RED, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nВи дійшли до 13 рівня. Вітаємо❗ Бажаєте продовжити❓", color=Fore.RED, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТи:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЗвісно поїхали❗", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🎮Автомат відкрився:", color=Fore.RED, delay=0.1)
    type_txt(txt="\n🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nО❗ це гра", color=Fore.CYAN, delay=0.1)
    play_sound("телопортування.wav")
    time.sleep(5)
    clear_scr()
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nПрокидайтесь майстре", delay=0.1)
    time.sleep(1)  
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nА❗ Що❓ Де я❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nВітаю у Теракарані.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТеракарана - це небезпечне місце, загроза чатує на кожному кроці,", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nперемогк тут не здобути бездосвівченого провідника.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЦей провідник я, самурай 🧙🏼Окіно.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n😔Але усі мої майстри загинули. Кожен меч( | ) це один майстер.", delay=0.1)
    print("""
    |||||||||||||||||||||||||||||||
    |||||||||||||||||||||||||||||||
    |||||||||||||||||||||||||||||||
    |||||||||||||||||||||||||||||||
    |||||||||||||||||||||||||||||||
""")
    clear_scr()
    time.sleep(2)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nА що я маю зробити❗", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nПотрібно пройти через 🌳Ліс Прикрощів, 🏔️Гори Істерії та Лабіринт 🟥Червоного 🐉Дракона.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nУ лабіринті 💤спить 🟥Червоний 🐉Дракон він охороняє катана-ключ🗝️.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЯкщо хочеш можеш спробувати сам пройти через 🌳Ліс Прикрощів, але в ньому є розвилка.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЯкщо звернути не тудити потрапиш не до 🏔️Гір Істерії, а до ілюзії і там буде дещо страшніше ніж 🐉дракон", delay=0.1)
    time.sleep(1)
#разом з Окіно в горах
def Okino_gory():
    clear_scr()
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЩоб піднятися на 🏔️Гори  Істерії нам потрібен гарпун, його можна купити у торговця, але можна і без нього обійтися.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nУ тебе зпочатку є 1️⃣0️⃣0️⃣ балів гарпун коштує 8️⃣0️⃣ а трос поганий 2️⃣0️⃣ на хороший не вистачить", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nКупуємо гарпун❓(так чи ні)", delay=0.1)
    time.sleep(1)
    gar=input("")
    if gar=="так":
        garpun()
    else:
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nЦе займе трохи більше часу.", delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🧌Троль:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nВам потрібно на верх я знаю де телепорт", color=Fore.LIGHTMAGENTA_EX , delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nПокажи нам його і ми заплатимо тобі 5️⃣0️⃣ балів", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🧌Троль:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nТоді за мною", color=Fore.LIGHTMAGENTA_EX , delay=0.1)
        time.sleep(1)
        type_txt(txt="\n       **********         ", color=Fore.CYAN, delay=0.1)
        play_sound("телопортування.wav ")
        time.sleep(5)
        play_sound("die3.wav")
        time.sleep(4)
        color_txt(txt="😔Нажаль ви програли❌. Не можна довіряти незнайомцям")
        lose() 
#один в лісі
def aloneForest():
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЦікаво чому цей ліс так називають❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("перевертні.wav")
    type_txt(txt="\nЧорт що робити❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    perewer=int(input("1️⃣-⚔️битися, 2️⃣-обійти"))
    if perewer==1:
        play_sound("удар.wav")
        time.sleep(1)
        die=random.randint(1,5)
        if die==random.randint(1,8):
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("die2.wav")
            time.sleep(4)
            color_txt(txt="😔Нажаль ви програли❌. Перевертні сильні")
            lose()
        else:
            play_sound("удар.wav")
            time.sleep(1)
            print("🥷🏼 ⚔️⚔️ 🐺🐺")
            play_sound("удар.wav")
            time.sleep(1)
            type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
            time.sleep(5)
            type_txt(txt="\n😮‍💨Ледве впорався", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
    else:
        pechera1()
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТак а ось і розвилка", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
#зустріч з Окіно в горах
def Okino_gory1():
    clear_scr()
    play_sound("пройшов.wav")
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЩоб піднятися на 🏔️Гори  Істерії нам потрібен гарпун, його можна купити у торговця, але можна і без нього обійтися.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nУ тебе зпочатку є 1️⃣0️⃣0️⃣ балів гарпун коштує 8️⃣0️⃣ а трос поганий 2️⃣0️⃣ на хороший не вистачить", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nКупуємо гарпун❓(так чи ні)", delay=0.1)
    time.sleep(1)
    gar=input("")
    if gar=="так":
        garpun1()
    else:
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nЦе займе трохи більше часу.", delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🧌Троль:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nВам потрібно на верх я знаю де телепорт", color=Fore.LIGHTMAGENTA_EX , delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nПокажи нам його і ми заплатимо тобі 5️⃣0️⃣ балів", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🧌Троль:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nТоді за мною", color=Fore.LIGHTMAGENTA_EX , delay=0.1)
        time.sleep(1)
        type_txt(txt="\n       **********         ", color=Fore.CYAN, delay=0.1)
        play_sound("телопортування.wav ")
        time.sleep(5)
        play_sound("die3.wav")
        time.sleep(4)
        color_txt(txt="😔Нажаль ви програли❌. Не можна довіряти незнайомцям")
        lose() 
#лабіринт
def labir():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nУ лабіринті багато пасток але разом ми швидко пройдем.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n        ****через 1️⃣0️⃣ хв****         ", delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nНам залишилося декілька поворотів.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nОбережно тут пастка❗", delay=0.01)
    time.sleep(1)
    type_txt(txt="\n😮‍💨Хух. Спробуй вивбрати шлях на ліво чи направо.", delay=0.1)
    time.sleep(1)
    labir=input("1️⃣-параво, 2️⃣-ліво")
    if labir==2:
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nМмм да з 🍀вдачою у тебе проблеми.", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nНічого страшного, добре що я занаю шлях.", delay=0.1)
        time.sleep(1)
    else:
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nОго, ти вгадав❗", delay=0.1)
        time.sleep(1)
    type_txt(txt="\nІ так за тим поворотом 🐉дракон, якщо пощастить ти забереш катана-ключ🗝️ безшумно🤫.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nІ 🐉дракон не прокиняться. Давай, але памятай в дракона є вразливе місце а спині.", delay=0.1)
    time.sleep(1)
    stels=random.randint(1,4)
    if stels==random.randint(1,3):
        play_sound("БОССС.wav")
        type_txt(txt="🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nОй де катана-ключ🗝️❓ Ось❗", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        final=input("вибери число від 1️⃣ до 5️⃣")
        if final==random.randint(1,5):
            clear_scr()
            type_txt(txt="\n🎮Автомат:", color=Fore.RED, delay=0.1)
            time.sleep(1)
            type_txt(txt="\nВітаємо ви перемогли❗", color=Fore.RED, delay=0.1)
            time.sleep(1)
            play_sound("пройшов.wav")
            time.sleep(3)
            clear_scr()
            type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
            type_txt(txt="\nАааааааааааа❗ Прогулявся.", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
        else:
            play_sound("die1.wav")
            time.sleep(4)
            color_txt(txt="😔Нажаль ви програли❌. Дракони надзвичайно сильні")
            lose() 
    else:
        clear_scr()
        type_txt(txt="\n🎮Автомат:", color=Fore.RED, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nВітаємо ви перемогли!", color=Fore.RED, delay=0.1)
        time.sleep(1)
        play_sound("пройшов.wav")
        time.sleep(3)
        clear_scr()
        type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nАааааааааааа❗ Прогулявся.", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
#спуск у нікуди
def scary():
    clear_scr()
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТам просто темнота.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n        ****в низу****", color=Fore.CYAN, delay=0.1)
    time.sleep(2)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТут моторошно.😨 Ще й ці звуки. Але я пройду.", color=Fore.CYAN, delay=0.1)
    play_sound("спуск у страх.wav")
    time.sleep(10)
    scary=random.randint(1,8)
    if scary==random.randint(1,8):
        play_sound("die2.wav")
        time.sleep(4)
        color_txt(txt="😔Нажаль ви програли❌. Вас убила темрява.")
        lose()
    else:
        time.sleep(10)
        type_txt(txt="\n😮‍💨Хух пройшов", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
#не туди
def notleft():
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nОкіно❗ Дивно де він❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nСтоп🤔 він казав 'якщо мене не буде ти прийшов не туди' ", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("не туди.wav")
    time.sleep(20)
    clear_scr()
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЧорт❗ Що робити❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nПрийдеться йти самому, у пекла.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТак що в нас тут, друхлявий підвісний міст і спуск.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    b=input("1️⃣-міст(швидко), 2️⃣-спуск(довше)")
    if b==1:
        type_txt(txt="\nПіду мостом", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        bridge=random.randint(1,5)
        if bridge==random.randint(1,5):
            play_sound("die3.wav")
            time.sleep(4)
            color_txt(txt="😔Нажаль ви програли❌. Міст трухлявий.")
            lose()
        else:
            type_txt(txt="\n😮‍💨Пощастило", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
    else:
        type_txt(txt="\nПіду спуском", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        scary()
    clear_scr()
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЦікаво🤔 що означало 'і там буде дещо страшніше ніж дракон' певно зараз дізнаюсь", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
#дещо страшніше
def somewhat_scarier():
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nДе ж мені шукати катану-ключа🗝️", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nЩ-щ-що ц-ц-це❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("rev_dinozavra.wav")
    time.sleep(4)
    type_txt(txt="\nЦ-ц-це 🦖ди-ди-но-завр❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("dinozavr_shagaet.wav")
    time.sleep(5)
    type_txt(txt="\nЯк повз нього пройти❓ Ось там за ним катана-ключ🗝️.", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    play_sound("dinozavr_shagaet.wav")
    time.sleep(5)
    dino=random.randint(1,10)
    if dino==3:
        clear_scr()
        type_txt(txt="\n🎮Автомат:", color=Fore.RED, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nВітаємо ви перемогли❗", color=Fore.RED, delay=0.1)
        time.sleep(1)
        play_sound("пройшов.wav")
        time.sleep(3)
        clear_scr()
        type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nАааааааааааа❗ Прогулявся.", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
    else:
        play_sound("rev_dinozavra.wav")
        time.sleep(4)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\nОй❗ Ааааааааа❗", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        b=random.randint(1,100)
        if b==random.randint(50,100):
            play_sound("die1.wav")
            time.sleep(4)
            color_txt(txt="😔Нажаль ви програли❌. Динозаври небезпечні.")
            lose()
        else:
            type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
            time.sleep(1)
            type_txt(txt="\nМайстре❗ Я врятую вас❗", delay=0.1)
            time.sleep(1)
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("ranenogo_dinozavra.wav")
            time.sleep(3)
            type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
            type_txt(txt="\nОкіно, як ти мене знашов❓", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
            type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
            time.sleep(1)
            type_txt(txt="\nНе важливо беріть катану-ключа🗝️.", delay=0.1)
            time.sleep(1)
            clear_scr()
            type_txt(txt="\n🎮Автомат:", color=Fore.RED, delay=0.1)
            time.sleep(1)
            type_txt(txt="\nВітаємо ви перемогли❗", color=Fore.RED, delay=0.1)
            time.sleep(1)
            play_sound("пройшов.wav")
            time.sleep(3)
            clear_scr()
            type_txt(txt="🧑🏼‍💼Ти:", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
            type_txt(txt="\nАааааааааааа❗ Прогулявся.", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
#разом з Окіно
def Okino():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nТоді рушаймо❗", delay=0.1)
    time.sleep(1)
    play_sound("нове_завдання.wav ")
    time.sleep(1)
    play_sound("ходьба.wav ")
    time.sleep(5)
    type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\nА чому цей 🌳ліс так називають❓", color=Fore.CYAN, delay=0.1)
    time.sleep(1)
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nВсе у цьому 🌳лісі намагається вас убити, навіть земля буває оманлива.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nСтій попереду 🌿ліани душителі.", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nВибирай битися чи обійти❓", delay=0.1)
    time.sleep(1)
    liany=int(input("1️⃣-битися, 2️⃣-обійти"))
    if liany==1:
        play_sound("удар.wav")
        time.sleep(1)
        play_sound("удар.wav")
        time.sleep(1)
        print("🧙🏼 🥷🏼⚔️🌿")
        play_sound("удар.wav")
        time.sleep(1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(5)
        type_txt(txt="\nНу й гидота. Пішли звідци", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
    else:
        pechera()
    clear_scr()
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nНезабаром має бути розвила, ось там.", delay=0.1)
    time.sleep(1)
    play_sound("перевертні.wav")
    time.sleep(4)
    type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
    time.sleep(1)
    type_txt(txt="\nМайстре швидше біжіть на право❗ Я впораюсь з 🐺перевертнями і наздожену вас!", delay=0.1)
    time.sleep(1)
    help=int(input("1️⃣-допомогти Окіно, 2️⃣-бігти на право"))
    if help==1:
        play_sound("удар.wav")
        time.sleep(1)
        a=random.randint(1,8)
        if a==random.randint(1,8):
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("die1.wav")
            time.sleep(4)
            color_txt(txt="😔Нажаль ви програли❌. Превертні сильні")
            lose()
        else:
            print("🧙🏼🥷🏼 ⚔️⚔️ 🐺🐺")
            play_sound("удар.wav")
            time.sleep(1)
            play_sound("удар.wav")
            type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
            time.sleep(1)
            type_txt(txt="\nДякую майстре, а тепер побігли", delay=0.1)
            time.sleep(1)
            play_sound("ходьба.wav ")
            time.sleep(5)
            type_txt(txt="\n        *********       ", color=Fore.CYAN, delay=0.1)
            time.sleep(1)
            type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
            time.sleep(1)
            type_txt(txt="\nМи прийшли до 🏔️гір істерії", delay=0.1)
    else:
        play_sound("ходьба.wav ")
        time.sleep(5)
        type_txt(txt="\n        *********       ", color=Fore.CYAN, delay=0.1)
        type_txt(txt="\n🥷🏼Ти:", color=Fore.CYAN, delay=0.1)
        time.sleep(5)
        type_txt(txt="\nНе треба було його лишати самого. Ось він❗", color=Fore.CYAN, delay=0.1)
        time.sleep(1)
        type_txt(txt="\n🧙🏼Окіно:", delay=0.1)
        time.sleep(1)
        type_txt(txt="\nМи прийшли до гір істерії", delay=0.1)
    play_sound("пройшов.wav")
    Okino_gory()
#на одинці
def alone():
    type_txt(txt="\n🧙🏼Окіно:", delay=0.15)
    time.sleep(1)
    type_txt(txt="\nУдачі тобі я чекатиму тебе біля 🏔️Грі Істерії, якщо мене не буде ти прийшов не туди", delay=0.15)
    time.sleep(1)
    play_sound("нове  завдання.wav ")
    time.sleep(1)
    play_sound("ходьба.wav ")
    clear_scr()
    aloneForest()
    leforig=input("1️⃣-право, 2️⃣-ліво")
    if leforig==1:
        Okino_gory1()
        labir()
    else:
        notleft()
        somewhat_scarier()
#гра          
def game():
    prolog()
    type_txt(txt="\nТо мені тебе провести❓(так чи ні)", delay=0.15)
    time.sleep(1)
    okino=input("")
    if okino=="так":
        Okino()
    else:
        alone()
#функція меню гри
def menu():
    global sound_on, sound_txt, menu
    clear_scr()
    play_sound("меню.wav")
    print(art)
    time.sleep(3)
    input(Fore.MAGENTA+"\n Натисніть Enter... щоб перейти до меню")
    while menu!=4 or menu!=1:
        clear_scr()
        color_txt(txt="🎮1.Розпочати гру🎮", color=Fore.LIGHTYELLOW_EX)
        time.sleep(1.5)
        color_txt(txt=f"📢2.Звук({sound_txt})📢", color=Fore.LIGHTYELLOW_EX)
        time.sleep(1.5)
        color_txt(txt="📋3.Про гру📋", color=Fore.LIGHTYELLOW_EX)
        time.sleep(1.5)
        color_txt(txt="❌4.Вийти з гри❌", color=Fore.LIGHTYELLOW_EX)
        time.sleep(1.5)
        menu=int(input(Fore.MAGENTA+"\n Зробіть вибір:"))
        if menu==1:
           game() 
        elif menu==2:
            if sound_on:
                sound_on=False
                sound_txt="ВИКЛ"
            else:
                sound_on=True
                sound_txt="ВКЛ"
        elif menu==3:
            clear_scr()
            color_txt(txt="©️Автор - Пребойчук Артем Володимирович©️", color=Fore.RED)
            time.sleep(1.5)
            color_txt(txt="📅Дата створення - 03.05.2025-10.05.2025📅", color=Fore.RED)
            time.sleep(1.5)
            color_txt(txt="📋За мотивами - мультсеріалу Лего Ніндзяго: Майстри Спінжитсу. Верховна Імперія (12 сезон)📋", color=Fore.RED)
            time.sleep(1.5)
            input(Fore.MAGENTA+"\n Натисніть Enter... щоб перейти до меню")
        elif menu==4:
            clear_scr()
            color_txt(txt="Шкода😔 До зустрічі")
            time.sleep(1.5)
            clear_scr()
            break

menu()